### PR TITLE
Add MoreFlags addon

### PR DESCRIPTION
**Pull request by lijinhong11**

### CODE REVIEW

**Comment by lijinhong11** [comment]
bump?

**Comment by tastybento** [comment]
It's fine. Can you tell me more about your software? I had a look and it offers a few new flags?

**Comment by lijinhong11** [comment]
> It's fine. Can you tell me more about your software? I had a look and it offers a few new flags?

It just a addon for add more flags to islands. This is only 3 flags now (bc of no idea)

**Comment by tastybento** [comment]
Okay. I'll add but the site won't get refreshed until the weekend.

**Pull request merged**
